os:
  - linux

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y binutils-mingw-w64-i686
  - sudo apt-get install -y gcc-mingw-w64-i686 mingw-w64-tools
  - sudo apt-get install -y wine1.7
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y binfmt-support

language: c

compiler:
  - gcc

script:
  - cd master
  - unset CC
  - sudo update-binfmts --disable wine
  - ./config
  - ./Configure --cross-compile-prefix=i686-w64-mingw32- mingw
  - make depend
  - make
  - wineboot
  - sudo update-binfmts --enable wine
  - make test
