os:
  - linux

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-wine/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y binutils-mingw-w64-i686
  - sudo apt-get install -y gcc-mingw-w64-i686 mingw-w64-tools
  - sudo apt-get install -y build-essential

language: c

compiler:
  - gcc

script:
  - cd master
  - ./config
  - make depend
  - make
  - make test
